# Generated by Django 2.2.6 on 2020-04-14 16:35

import blog.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('name', models.CharField(max_length=100, verbose_name='Names')),
                ('surnames', models.CharField(max_length=120, verbose_name='Surnames')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('referential_image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Referential image')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('referential_image', models.ImageField(upload_to='categorys/', verbose_name='Referential image')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surnames', models.CharField(max_length=150, verbose_name='Surnames')),
                ('mail', models.EmailField(max_length=200, verbose_name='Email')),
                ('affair', models.CharField(max_length=100, verbose_name='Affair')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Socialnetworks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('twitter', models.URLField(verbose_name='Twitter')),
                ('instagram', models.URLField(verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Social Network',
                'verbose_name_plural': 'Social Networks',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('mail', models.EmailField(max_length=200, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('we', models.TextField(verbose_name='We')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Post title')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('referential_image', models.ImageField(blank=True, height_field='height_field', max_length=255, null=True, upload_to=blog.models.upload_locatio, verbose_name='Referential image', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False, verbose_name='Published / Not Published')),
                ('publication_date', models.DateField(verbose_name='Publication date')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('tags', models.ManyToManyField(to='blog.Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-publication_date', '-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
            ],
        ),
    ]
