# Generated by Django 2.2.6 on 2020-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('modification_date', models.DateField(auto_now=True, verbose_name='Modification date')),
                ('removal_date', models.DateField(auto_now=True, verbose_name='Elimination Date')),
                ('name', models.CharField(max_length=100, verbose_name='Names')),
                ('surnames', models.CharField(max_length=120, verbose_name='Surnames')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('description', models.TextField(verbose_name='Description')),
                ('referential_image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Referential image')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
